#include "ItemDefinitions.hpp"

const std::map<size_t, Item_t> k_WeaponInfo =
{
	{1, {"Desert Eagle", "WEAPON_DEAGLE", "models/weapons/v_pist_deagle.mdl", "deagle"}},
	{2, {"Dual Berettas", "WEAPON_ELITE", "models/weapons/v_pist_elite.mdl", "elite"}},
	{3, {"Five-SeveN", "WEAPON_FIVESEVEN", "models/weapons/v_pist_fiveseven.mdl", "fiveseven"}},
	{4, {"Glock-18", "WEAPON_GLOCK", "models/weapons/v_pist_glock18.mdl", "glock"}},
	{7, {"AK-47", "WEAPON_AK47", "models/weapons/v_rif_ak47.mdl", "ak47"}},
	{8, {"AUG", "WEAPON_AUG", "models/weapons/v_rif_aug.mdl", "aug"}},
	{9, {"AWP", "WEAPON_AWP", "models/weapons/v_snip_awp.mdl", "awp"}},
	{10, {"FAMAS", "WEAPON_FAMAS", "models/weapons/v_rif_famas.mdl", "famas"}},
	{11, {"G3SG1", "WEAPON_G3SG1", "models/weapons/v_snip_g3sg1.mdl", "g3sg1"}},
	{13, {"Galil AR", "WEAPON_GALILAR", "models/weapons/v_rif_galilar.mdl", "galilar"}},
	{14, {"M249", "WEAPON_M249", "models/weapons/v_mach_m249para.mdl", "m249"}},
	{16, {"M4A4", "WEAPON_M4A1", "models/weapons/v_rif_m4a1.mdl", "m4a1"}},
	{17, {"MAC-10", "WEAPON_MAC10", "models/weapons/v_smg_mac10.mdl", "mac10"}},
	{19, {"P90", "WEAPON_P90", "models/weapons/v_smg_p90.mdl", "p90"}},
	{24, {"UMP-45", "WEAPON_UMP45", "models/weapons/v_smg_ump45.mdl", "ump45"}},
	{25, {"XM1014", "WEAPON_XM1014", "models/weapons/v_shot_xm1014.mdl", "xm1014"}},
	{26, {"PP-Bizon", "WEAPON_BIZON", "models/weapons/v_smg_bizon.mdl", "bizon"}},
	{27, {"MAG-7", "WEAPON_MAG7", "models/weapons/v_shot_mag7.mdl", "mag7"}},
	{28, {"Negev", "WEAPON_NEGEV", "models/weapons/v_mach_negev.mdl", "negev"}},
	{29, {"Sawed-Off", "WEAPON_SAWEDOFF", "models/weapons/v_shot_sawedoff.mdl", "sawedoff"}},
	{30, {"Tec-9", "WEAPON_TEC9", "models/weapons/v_pist_tec9.mdl", "tec9"}},
	{31, {"Zeus x27", "WEAPON_TASER", "models/weapons/v_eq_taser.mdl", "taser"}},
	{32, {"P2000", "WEAPON_HKP2000", "models/weapons/v_pist_hkp2000.mdl", "hkp2000"}},
	{33, {"MP7", "WEAPON_MP7", "models/weapons/v_smg_mp7.mdl", "mp7"}},
	{34, {"MP9", "WEAPON_MP9", "models/weapons/v_smg_mp9.mdl", "mp9"}},
	{35, {"Nova", "WEAPON_NOVA", "models/weapons/v_shot_nova.mdl", "nova"}},
	{36, {"P250", "WEAPON_P250", "models/weapons/v_pist_p250.mdl", "p250"}},
	{38, {"SCAR-20", "WEAPON_SCAR20", "models/weapons/v_snip_scar20.mdl", "scar20"}},
	{39, {"SG 553", "WEAPON_SG556", "models/weapons/v_rif_sg556.mdl", "sg556"}},
	{40, {"SSG 08", "WEAPON_SSG08", "models/weapons/v_snip_ssg08.mdl", "ssg08"}},
	{42, {"Knife (Counter-Terrorists)", "WEAPON_KNIFE", "models/weapons/v_knife_default_ct.mdl", "knife_default_ct"}},
	{43, {"Flashbang", "WEAPON_FLASHBANG", "models/weapons/v_eq_flashbang.mdl", "flashbang"}},
	{44, {"HE Grenade", "WEAPON_HEGRENADE", "models/weapons/v_eq_fraggrenade.mdl", "hegrenade"}},
	{45, {"Smoke Grenade", "WEAPON_SMOKEGRENADE", "models/weapons/v_eq_smokegrenade.mdl", "smokegrenade"}},
	{46, {"Molotov", "WEAPON_MOLOTOV", "models/weapons/v_eq_molotov.mdl", "inferno"}},
	{47, {"Decoy Grenade", "WEAPON_DECOY", "models/weapons/v_eq_decoy.mdl", "decoy"}},
	{48, {"Incendiary Grenade", "WEAPON_INCGRENADE", "models/weapons/v_eq_incendiarygrenade.mdl", "inferno"}},
	{49, {"C4 Explosive", "WEAPON_C4", "models/weapons/v_ied.mdl"}},
	{59, {"Knife (Terrorists)", "WEAPON_KNIFE_T", "models/weapons/v_knife_default_t.mdl", "knife_t"}},
	{60, {"M4A1-S", "WEAPON_M4A1_SILENCER", "models/weapons/v_rif_m4a1_s.mdl", "m4a1_silencer"}},
	{61, {"USP-S", "WEAPON_USP_SILENCER", "models/weapons/v_pist_223.mdl", "usp_silencer"}},
	{63, {"CZ75 Auto", "WEAPON_CZ75A", "models/weapons/v_pist_cz_75.mdl", "cz75a"}},
	{64, {"R8 Revolver", "WEAPON_REVOLVER", "models/weapons/v_pist_revolver.mdl", "revolver"}},
	{500, {"Bayonet", "WEAPON_KNIFE_BAYONET", "models/weapons/v_knife_bayonet.mdl", "bayonet"}},
	{505, {"Flip Knife", "WEAPON_KNIFE_FLIP", "models/weapons/v_knife_flip.mdl", "knife_flip"}},
	{506, {"Gut Knife", "WEAPON_KNIFE_GUT", "models/weapons/v_knife_gut.mdl", "knife_gut"}},
	{507, {"Karambit", "WEAPON_KNIFE_KARAMBIT", "models/weapons/v_knife_karam.mdl", "knife_karambit"}},
	{508, {"M9 Bayonet", "WEAPON_KNIFE_M9_BAYONET", "models/weapons/v_knife_m9_bay.mdl", "knife_m9_bayonet"}},
	{509, {"Huntsman Knife", "WEAPON_KNIFE_TACTICAL", "models/weapons/v_knife_tactical.mdl", "knife_tactical"}},
	{512, {"Falchion Knife", "WEAPON_KNIFE_FALCHION", "models/weapons/v_knife_falchion_advanced.mdl", "knife_falchion"}},
	{514, {"Bowie Knife", "WEAPON_KNIFE_SURVIVAL_BOWIE", "models/weapons/v_knife_survival_bowie.mdl", "knife_survival_bowie"}},
	{515, {"Butterfly Knife", "WEAPON_KNIFE_BUTTERFLY", "models/weapons/v_knife_butterfly.mdl", "knife_butterfly"}},
	{516, {"Shadow Daggers", "WEAPON_KNIFE_PUSH", "models/weapons/v_knife_push.mdl", "knife_push"}}
};

const std::vector<WeaponName_s> k_KniveNames =
{
	{0, "\xe9\xbb\x98\xe8\xae\xa4"},
	{500, "\xe5\x88\xba\xe5\x88\x80"},
	{505, "\xe6\x8a\x98\xe5\x8f\xa0\xe5\x88\x80"},
	{506, "\xe6\x9d\x80\xe7\x8c\xaa\xe5\x88\x80"},
	{507, "\xe7\x88\xaa\xe5\xad\x90\xe5\x88\x80"},
	{508, "M9\xe5\x88\xba\xe5\x88\x80"},
	{509, "\xe7\x8c\x8e\xe6\x9d\x80\xe8\x80\x85\xe5\x8c\x95\xe9\xa6\x96"},
	{512, "\xe5\xbc\xaf\xe5\x88\x80"},
	{514, "\xe9\xb2\x8d\xe4\xbc\x8a\xe7\x8c\x8e\xe5\x88\x80"},
	{515, "\xe8\x9d\xb4\xe8\x9d\xb6\xe5\x88\x80"},
	{516, "\xe6\x9a\x97\xe5\xbd\xb1\xe5\x8f\x8c\xe5\x8c\x95"}
};

const std::vector<WeaponName_t> k_WeaponNames =
 {
    {42, "Knife"},
    {7,  "AK-47"},
    {8,  "AUG"},
    {9,  "AWP"},
    {63, "CZ75 Auto"},
    {1,  "Desert Eagle"},
    {2,  "Dual Berettas"},
    {10, "FAMAS"},
	{3,  "Five-SeveN" },
    {11, "G3SG1"},
    {13, "Galil AR"},
    {4,  "Glock-18"},
    {14, "M249"},
    {60, "M4A1-S"},
    {16, "M4A4"},
    {17, "MAC-10"},
    {27, "MAG-7"},
    {33, "MP7"},
    {34, "MP9"},
    {28, "Negev"},
    {35, "Nova"},
    {32, "P2000"},
    {36, "P250"},
    {19, "P90"},
    {26, "PP-Bizon"},
    {64, "R8 Revolver"},
    {29, "Sawed-Off"},
    {38, "SCAR-20"},
    {40, "SSG 08"},
    {39, "SG 553"},
    {30, "Tec-9"},
    {24, "UMP-45"},
    {61, "USP-S"},
    {25, "XM1014"},
};

const std::vector<QualityName_t> k_QualityNames =
{
	{0, "\xe9\xbb\x98\xe8\xae\xa4"},
	{1, "\xe7\xba\xaf\xe6\xad\xa3"},
	{2, "\xe6\x9c\x80\xe4\xbd\xb3\xe9\x80\x89\xe6\x8b\xa9"},
	{3, "\xe5\xbc\x82\xe5\xb8\xb8"},
	{5, "\xe7\xa4\xbe\xe5\x8c\xba"},
	{6, "\xe5\xbc\x80\xe5\x8f\x91\xe8\x80\x85"},
	{7, "\xe8\x87\xaa\xe5\x88\xb6"},
	{8, "\xe5\xae\x9a\xe5\x88\xb6"},
	{9, "\xe4\xb8\x8d\xe8\xa7\x84\xe5\x88\x99"},
	{10, "\xe5\xae\x8c\xe6\x95\xb4\xe7\x89\x88"},
	{12, "\xe7\xab\x9e\xe6\x8a\x80"}
};

